import StructuralNonExhaustibility.Core.ReflexiveSystem
import StructuralNonExhaustibility.Theorems.NoTotalExhaustion
import StructuralNonExhaustibility.Theorems.InternalizationNotTotalization
import StructuralNonExhaustibility.Bridges.ToSemanticSelfDescription
